In [3]:
import numpy  as np
import pandas as pd
import matplotlib.pyplot as pl
import seaborn as sb


%matplotlib inline

In [4]:
df = pd.read_csv('iris.csv')

In [5]:
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.054000           3.758667   
std             0.828066          0.433594           1.764420   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.198667  
std            0.763161  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [6]:
df.target.unique()

array(['SETOSA', 'VERSICOLOR', 'VIRGINICA'], dtype=object)

In [7]:
X = df.ix[:,0:4].values  ## methodo ix[linhas,colunas]
X

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [8]:
y = df[['target']].values.ravel()
y

array(['SETOSA', 'SETOSA', 'SETOSA', 'SETOSA', 'SETOSA', 'SETOSA',
       'SETOSA', 'SETOSA', 'SETOSA', 'SETOSA', 'SETOSA', 'SETOSA',
       'SETOSA', 'SETOSA', 'SETOSA', 'SETOSA', 'SETOSA', 'SETOSA',
       'SETOSA', 'SETOSA', 'SETOSA', 'SETOSA', 'SETOSA', 'SETOSA',
       'SETOSA', 'SETOSA', 'SETOSA', 'SETOSA', 'SETOSA', 'SETOSA',
       'SETOSA', 'SETOSA', 'SETOSA', 'SETOSA', 'SETOSA', 'SETOSA',
       'SETOSA', 'SETOSA', 'SETOSA', 'SETOSA', 'SETOSA', 'SETOSA',
       'SETOSA', 'SETOSA', 'SETOSA', 'SETOSA', 'SETOSA', 'SETOSA',
       'SETOSA', 'SETOSA', 'VERSICOLOR', 'VERSICOLOR', 'VERSICOLOR',
       'VERSICOLOR', 'VERSICOLOR', 'VERSICOLOR', 'VERSICOLOR',
       'VERSICOLOR', 'VERSICOLOR', 'VERSICOLOR', 'VERSICOLOR',
       'VERSICOLOR', 'VERSICOLOR', 'VERSICOLOR', 'VERSICOLOR',
       'VERSICOLOR', 'VERSICOLOR', 'VERSICOLOR', 'VERSICOLOR',
       'VERSICOLOR', 'VERSICOLOR', 'VERSICOLOR', 'VERSICOLOR',
       'VERSICOLOR', 'VERSICOLOR', 'VERSICOLOR', 'VERSICOLOR',
       'VERSICOLO

# USANDO ACURÁCIA

## Holdout folder

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.8, random_state=42)

In [11]:
X_train.shape, y_train.shape

((30, 4), (30,))

In [12]:
X_test.shape, y_test.shape

((120, 4), (120,))

## Acurácia com KNN

In [13]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)

knn.score(X_test, y_test)

0.97499999999999998

## Acurácia com Árvore de decisão

In [14]:
from sklearn import tree
tree = tree.DecisionTreeClassifier()
tree.fit(X_train, y_train)
tree.score(X_test,y_test)

0.93333333333333335

## Acurácia com SVM

In [15]:
from sklearn import svm
svm = svm.SVC()
svm.fit(X_train, y_train)
svm.score(X_test,y_test)

0.97499999999999998

## Acurácia com Rede Neural MLP 
(multi-layer perceptron)

In [16]:
from sklearn.neural_network import MLPClassifier
rn = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(2, 2), random_state=0)
rn.fit(X_train,y_train)
rn.score(X_test, y_test)

0.95833333333333337

## Acurácia com Nayve Bayes

In [17]:
from sklearn.naive_bayes import GaussianNB
nayB = GaussianNB()
nayB.fit(X_train, y_train)
nayB.score(X_test, y_test)

0.94999999999999996

# Usando K-Fold
importando a biblioteca 

In [18]:
from sklearn.model_selection import cross_val_score

#### Knn com K-Fold

In [54]:
scores = cross_val_score(knn, X, y, cv=50)
scores.mean()

0.96666666666666667

#### Árvore de decisão com K-Fold

In [20]:
scores = cross_val_score(tree, X, y, cv=10)
scores.mean()

0.95999999999999996

#### SVM com K-Fold

In [21]:
scores = cross_val_score(svm, X, y, cv=10)
scores.mean()

0.98000000000000009

#### Rede Neural MLP com K-fold

In [22]:
scores = cross_val_score(rn, X, y, cv=10)
scores.mean()

0.98000000000000009

#### Nayve Bayes com K-fold

In [41]:
scores = cross_val_score(nayB, X, y, cv=10)
scores.mean()

0.95333333333333337

# MATRIZ DE CONFUSÃO

#### KNN

In [42]:
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
y_pred = cross_val_predict(knn,X,y,cv=5)
conf_mat = confusion_matrix(y,y_pred, labels=['VERSICOLOR', 'VIRGINICA','SETOSA'])
conf_mat

array([[47,  3,  0],
       [ 2, 48,  0],
       [ 0,  0, 50]])

# Curva ROC

In [45]:
from sklearn.metrics import precision_recall_fscore_support

In [48]:
p, r, f, s = precision_recall_fscore_support(y, y_pred)

In [49]:
p

array([ 1.        ,  0.95918367,  0.94117647])